// Onboarding Screens | TODO: Replace instances within the app
export const WELCOME_SCREEN = 'WELCOME_SCREEN';
export const LOGIN_SCREEN = 'LOGIN_SCREEN';
export const PASSPORT_TAB_SCREEN = 'PASSPORT_TAB_SCREEN';
export const PASSPORT_SCREEN = 'PASSPORT_SCREEN';
export const PASSPORT_INFO = 'PASSPORT_INFO';
export const NEW_PASSPORT_SCREEN = 'NEW_PASSPORT_SCREEN';
export const EXPLORER_TAB_SCREEN = 'EXPLORER_TAB_SCREEN';
export const EXPLORER_SCREEN = 'EXPLORER_SCREEN';
export const POZZLE_ACTIVITY_TAB_SCREEN = 'POZZLE_ACTIVITY_TAB_SCREEN';
export const POZZLE_ACTIVITY_SCREEN = 'POZZLE_ACTIVITY_SCREEN';
export const ONBOARDING_SCREEN = 'ONBOARDING_SCREEN';
export const PLANET_SCREEN = 'PLANET_SCREEN';
export const VIDEO_SCREEN = 'VIDEO_SCREEN';
export const EARTH_SCREEN = 'EARTH_SCREEN';
export const DISCOVERY_SCREEN = "DISCOVERY_SCREEN";
